# configuration file for MYSQL
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MyAQL5InnoDBDialect

# JPA settings
  jpa.hibernate.ddl_auto: create  # can use update also